# Uncomment the next line to define a global platform for your project
platform :ios, '17.6'

workspace 'DevKitPro'

def shared_pods
  pod 'RxSwift'
  pod 'APIKit'
  pod 'R.swift'
#  pod 'RealmSwift'
  pod 'Swinject'
  pod 'SwinjectStoryboard'
  pod 'Alamofire'
  
  # Development tools
  pod 'SwiftLint'
  pod 'SwiftFormat/CLI'
end

target 'DevKitPro' do
  
  xcodeproj 'DevKitPro.xcodeproj'
  use_frameworks!
  shared_pods
  
  target 'DevKitProTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick', '~> 5.0'
    pod 'Nimble', '~> 10.0'
  end

  target 'DevKitProUITests' do
    # Pods for testing
    pod 'KIF', '~> 3.8'
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.6'
            config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        end
    end
end
